### ISSUE TITLE
CSS not loading correctly

### ISSUE THREAD

**Issue by vsivsi** [joehand/are-you-around#2]
Now that I got it to build, I get the following warning when running `npm install`.

```
npm WARN peerDependencies The peer dependency insert-css@^1.0.0 included from sheetify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

My npm version:

```
npm --version
2.15.9
```

That has the effect (I think) of causing the CSS bundle to not be created properly.

In the console at runtime:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/vsi/are-you-around/app/bundle.css 
```

![screen shot 2016-08-30 at 4 02 46 pm](https://cloud.githubusercontent.com/assets/428642/18110187/3b27fbd4-6ecb-11e6-9646-f9592a1354cf.png)

**Comment by vsivsi** [comment]
Okay, got it to work.

Firstly, globally installed `browserify` is a dependency:  `npm install -g browserify`

Secondly, the instructions say to run `npm run rebuild` but to correctly build the bundle, you need to run `npm run build` instead.  Everything looks good now!

**Comment by joehand** [comment]
Thanks for the bug reports! 

I just updated the start script to make it work always on the first run.

**Comment by vsivsi** [comment]
Great! You should be able to see my status at: 

`49BBB609E4DEB21A9DF89B627725BA0340C970DAB0DAC05BDDA3C731E0D6D1C3`
